# Generated by Django 5.2.8 on 2025-11-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Przesad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(help_text='Przesad — krotki tekst', max_length=180)),
                ('opis_pochodzenia', models.TextField(blank=True, help_text='Skad sie wzial przesad (opcjonalnie)')),
            ],
            options={
                'verbose_name': 'Przesad',
                'verbose_name_plural': 'Przesady',
            },
        ),
        migrations.CreateModel(
            name='Egzamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('przedmiot', models.CharField(help_text='Nazwa przedmiotu', max_length=120)),
                ('data', models.DateField(help_text='Data egzaminu')),
                ('godzina', models.TimeField(help_text='Godzina egzaminu')),
                ('miejsce', models.CharField(help_text='Sala lub budynek', max_length=120)),
                ('typ', models.CharField(choices=[('pisemny', 'Pisemny'), ('ustny', 'Ustny'), ('projekt', 'Projekt'), ('inne', 'Inne')], default='pisemny', max_length=20)),
            ],
            options={
                'verbose_name': 'Egzamin',
                'verbose_name_plural': 'Egzaminy',
                'ordering': ['data', 'godzina'],
                'indexes': [models.Index(fields=['data', 'godzina'], name='main_egzami_data_cce616_idx'), models.Index(fields=['typ'], name='main_egzami_typ_e7d6f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Porada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField(help_text='Tresc porady')),
                ('kategoria', models.CharField(choices=[('motywacja', 'Motywacja'), ('nauka', 'Nauka'), ('zdrowie', 'Zdrowie'), ('inne', 'Inne')], default='motywacja', max_length=20)),
            ],
            options={
                'verbose_name': 'Porada',
                'verbose_name_plural': 'Porady',
                'indexes': [models.Index(fields=['kategoria'], name='main_porada_kategor_b070a0_idx')],
            },
        ),
    ]
